[Variables]

;-----------------------
; LAYOUT

Stylesheet=Enigma Dark

;-----------------------
; GENERAL

Note1Path=#@#User\Notes\Notes.txt
Note2Path=#@#User\Notes\Tasks.txt
Note3Path=#@#User\Notes\About.txt
NoteHeight=200
Drive1=C
Drive2=D
Drive3=E
NetworkMaxDownload=125000000
NetworkMaxUpload=125000000
SystemGraphType=Floating
CalendarEventFile=#@#User\Calendars\Holidays.xml
CalendarShowEvents=1
CalendarExtraDays=1
CalendarLeadingZeroes=0
CalendarMondays=0
GalleryPath=%USERPROFILE%\Pictures
GallerySubfolders=1
GalleryPosition=Center
GalleryRatio=3/4
VolumeIncrement=5
TriptychInterval=30
TriptychDisabled=0
ProcessInterval=5

;-----------------------
; MUSIC

MusicPlayerType=10
MusicPlayer=Spotify

;-----------------------
; FEEDS

Feed1=https://news.google.com/rss?hl=en-US&gl=US&ceid=US:en
Feed2=https://news.google.com/rss/headlines/section/topic/TECHNOLOGY?hl=en-US&gl=US&ceid=US:en
Feed3=https://feeds.bbci.co.uk/news/world/rss.xml
Feed4=https://news.ycombinator.com/rss
Feed5=https://feeds.arstechnica.com/arstechnica/index
GmailUsername=YourUsernameHere
GmailPassword=YourPasswordHere
FacebookFeed=YourFacebookFeedHere
GoogleCalendar1=YourCalendarAddressHere
GoogleCalendar2=YourCalendarAddressHere
GoogleCalendar3=YourCalendarAddressHere
GoogleCalendar4=YourCalendarAddressHere
GoogleCalendar5=YourCalendarAddressHere
GoogleCalendar6=YourCalendarAddressHere
GoogleCalendar7=YourCalendarAddressHere
GoogleCalendar8=YourCalendarAddressHere
GoogleCalendarWriteEvents=1
RTMusername=YourUserNameHere
RTMpassword=YourPasswordHere
RTMlist1=YourListNumberHere
RTMlist2=YourListNumberHere
RTMlist3=YourListNumberHere
TwitterUsername=YourUsernameHere
TwitterPassword=YourPasswordHere

;-----------------------
; WORLD
GreetingName=Friend

WeatherCode=2459115
WeatherCodeName=New York
WeatherCodeLat=40.7128
WeatherCodeLon=-74.0060
Unit=f
World1WeatherCode=44418
World1WeatherCodeName=London
World1WeatherCodeLat=51.506321
World1WeatherCodeLon=-0.127140
World2WeatherCode=2514815
World2WeatherCodeName=Washington
World2WeatherCodeLat=38.9
World2WeatherCodeLon=-77.03
World3WeatherCode=455825
World3WeatherCodeName=Rio de Janeiro
World3WeatherCodeLat=-22.98
World3WeatherCodeLon=-43.2

;-----------------------
; APPS

App1=Chrome
App1Path=chrome.exe
App1PathHandle=chrome.exe
App1Label=WEB
App1Icon=#@#Images\Launcher\Chrome.#ColorImage#.png
App2=Notepad
App2Path=notepad.exe
App2PathHandle=notepad.exe
App2Label=TEXT
App2Icon=#@#Images\Launcher\Text.#ColorImage#.png
App3=Explorer
App3Path=explorer.exe
App3PathHandle=explorer.exe
App3Label=FILES
App3Icon=#@#Images\Launcher\Start.#ColorImage#.png
App4=Skype
App4Path=C:\Program Files\Skype\Phone\skype.exe
App4PathHandle=skype.exe
App4Label=CHAT
App4Icon=#@#Images\Launcher\Skype.#ColorImage#.png
App5=Rainmeter.net
App5Path=http://rainmeter.net/
App5Handle=rainmeter.exe
App5Label=FORUM
App5Icon=#@#Images\Launcher\Rainmeter.png

;-----------------------
; SEARCH

Search1=Google
Search1Command="http://google.com/search?q=$UserInput$"
Search1Icon=#@#Images\Search\Google.#ColorImage#.png
Search2=Wikipedia
Search2Command="http://en.wikipedia.org/wiki/$UserInput$"
Search2Icon=#@#Images\Search\Wiki.#ColorImage#.png
Search3=YouTube
Search3Command="http://www.youtube.com/results?search_query=$UserInput$"
Search3Icon=#@#Images\Search\YouTube.#ColorImage#.png
Search4=Twitter
Search4Command="https://twitter.com/#!/search/$UserInput$"
Search4Icon=#@#Images\Search\Twitter.#ColorImage#.png
Search5=Rainmeter.net
Search5Command="https://www.google.com/search?q=site%3Ahttp%3A%2F%2Frainmeter.net%2Fcms%2F%20$UserInput$"
Search5Icon=#@#Images\Search\Run.#ColorImage#.png
