;--------------------------------------------------------------------------------------------
; ENIGMA DARK
; These are the default user setting values for the Enigma Dark stylesheet. They are used by the Options skin to restore default values.
; You should not make changes to this file unless you know what you're doing. Instead, use Enigma Dark.inc to change your active personal settings.

[Variables]
DefaultColor1=236,236,242
DefaultColor2=177,78,255
DefaultColor3=58,51,96
DefaultColor4=42,37,71
DefaultColorLink=0,240,255
DefaultColorLink2=#*ColorLink*#,217
DefaultColorLink3=#*ColorLink*#,160
DefaultColorBorder=255,0,153
DefaultColorBorder2=#*ColorBorder*#, 128
DefaultColorBorder3=#*ColorBorder*#, 92
DefaultColorBorder4=42,37,71,220
DefaultColorPanel=22,18,40
DefaultColorPanel2=#*ColorPanel*#,128
DefaultColorFilter=13,11,26
DefaultColorFilter2=#*ColorFilter*#,192
DefaultColorFilter3=#*ColorFilter*#,128
DefaultColorEvent=252,238,10
DefaultColorEvent2=#*ColorEvent*#,92
DefaultColorTransparent=0,0,0,2
DefaultColorImage=W

DefaultSize1=10
DefaultSize4=7
DefaultSize3=8
DefaultSize2=9
DefaultFont=Trebuchet MS
DefaultSkinBackgroundAlpha=100
DefaultHideBordersTop=0
DefaultHideBordersBottom=1

DefaultSidebarWidth=200
DefaultSidebarSpacingFixed=1
DefaultSidebarAlpha=128
DefaultSidebarImage=#*@*#Images\Sidebar\SidebarLeft.#*ColorImage*#.jpg
DefaultSecondSidebarImage=#*@*#Images\Sidebar\SidebarRight.#*ColorImage*#.jpg

DefaultTaskbarHeight=44
DefaultTaskbarSpacingFixed=0
DefaultTaskbarAlpha=204
DefaultTaskbarImage=#*@*#Images\Taskbar\TaskbarTop.#*ColorImage*#.jpg
DefaultSecondTaskbarImage=#*@*#Images\Taskbar\TaskbarBottom.#*ColorImage*#.jpg
DefaultTaskbarMaxSkinWidth=200
DefaultTaskbarMinSkinWidth=60
DefaultTaskbarHideTriptych=1

DefaultSidebarClockFace=#*@*#Images\Clock\EnigmaClock.#*ColorImage*#.png
DefaultSidebarWorldClockFace=#*@*#Images\Clock\ChevronClock.#*ColorImage*#.png
DefaultTaskbarClockFace=#*@*#Images\Clock\ChevronClock.#*ColorImage*#.png